import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "rsuite/dist/rsuite-no-reset.min.css";
import { CustomProvider } from "rsuite";
import GeneralProvider from "@/context/GeneralProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "School system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>
          <GeneralProvider>{children}</GeneralProvider>
        </CustomProvider>
      </body>
    </html>
  );
}
